package Module7.Module5Update;


public enum Hotels {
    CALIFORNIA, REDISON, ROYAL, SKYHIGHT, KING,
    HILTON, PLASA, SKYTOWER, TOPPLACE, RIVERA,
    KIYV, SALUTE, OBERIG, INTURIST, INTERCONTINENTAL;

}
